app/blueprints/main/models.py
from app import db, login_manager
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(120), unique=True)
    first_name = db.Column(db.String(64))
    last_name = db.Column(db.String(64))
    password = db.Column(db.String(128))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    # todo: add a character avatar
    # todo: add a bio
    # todo: add a

    def hash_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)


@login_manager.user_loader
def user_loader(user_id):
    return User.query.get(int(user_id))


class Pokemon(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    game_id = db.Column(db.Integer)
    name = db.Column(db.String(128))
    height = db.Column(db.Integer)
    weight = db.Column(db.Integer)
    types = db.Column(db.String(128))
    abilities = db.Column(db.String(128))
    sprite = db.Column(db.String(128))
    description = db.Column(db.String(512))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)


pokemon_user = db.Table('pokemon_user',
                        db.Column('user_id', db.Integer, db.ForeignKey(
                            'user.id'), primary_key=True),
                        db.Column('pokemon_id', db.Integer, db.ForeignKey('pokemon.id'), primary_key=True))

app/__init__.py
from flask import Flask, flash, redirect, render_template, request, url_for
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__)

    app.config.from_object('config.Config')

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)


    from app.blueprints.main import bp as main_bp
    app.register_blueprint(blueprint=main_bp)

    from app.blueprints.user import bp as user_bp
    app.register_blueprint(blueprint=user_bp)

    from app.blueprints.api import bp as api_bp
    app.register_blueprint(blueprint=api_bp)

    from app.blueprints.auth import bp as auth_bp
    app.register_blueprint(blueprint=auth_bp)


    login_manager.login_view = 'auth.login'
    login_manager.login_message = 'Please log in to access this page.'
    login_manager.login_message_category = 'danger'

    return app

app/blueprints/api/__init__.py


from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix='/api')


from . import routes

app/blueprints/api/routes.py
from . import bp as app
from app.blueprints.main.models import User
from app import db
from flask import render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
import re

app/blueprints/main/__init__.py

from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='/')


from . import routes, models

app/blueprints/main/routes.py
from . import bp as app
from flask import render_template, request, redirect, url_for, flash, session
from app import db
from app.blueprints.main.models import User, Pokemon
from flask_login import current_user, login_required


@app.route('/', methods=['GET', 'POST'])
def home():
    pokemon = [Pokemon.query.filter_by(game_id=1).first(), Pokemon.query.filter_by(
        game_id=4).first(), Pokemon.query.filter_by(game_id=7).first()]
    return render_template('home.html.j2', user=current_user, pokemon=pokemon)


@app.route('/search/', methods=['GET', 'POST'])
@login_required
def search():
    name = request.form['name']
    print(name)
    pokemon = Pokemon.query.filter_by(name=name).first()
    return render_template('single.html.j2', user=current_user, pokemon=pokemon)


@app.route('/pokemon/<int:game_id>', methods=['GET', 'POST'])
@login_required
def pokemon(game_id):
    pokemon = Pokemon.query.filter_by(game_id=game_id).first()
    return render_template('single.html.j2', user=current_user, pokemon=pokemon)

app/blueprints/user/__init__.py
from flask import Blueprint

bp = Blueprint('user', __name__, url_prefix='/user')

from . import routes

app/blueprints/user/routes.py
from . import bp as app
from flask import render_template, request, redirect, url_for, flash, session
from app import db
from app.blueprints.main.models import User, Pokemon, pokemon_user
from flask_login import current_user, login_required


@app.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    pokemon = Pokemon.query.join(pokemon_user).filter_by(user_id=current_user.id).all()
    return render_template('profile.html.j2', user=current_user, pokemon=pokemon)

@app.route('/account/', methods=['GET', 'POST'])
@login_required
def account():
    return render_template('account.html.j2', user=current_user)


@app.route('/pick/<int:id>', methods=['POST'])
@login_required
def pick(id):
    pokemon = Pokemon.query.filter_by(game_id=id).first()
    try:
        statement = pokemon_user.insert().values(pokemon_id=id, user_id=current_user.id)
        db.session.execute(statement)
        db.session.commit()
        flash(f'Added {pokemon.name.title()} to your page!', 'success')
    except Exception as e:
        flash(f'Error picking {pokemon.name.title()}', 'danger')
    return redirect(url_for('user.profile'))

app/templates/account.html.j2
{% extends 'base.html.j2' %}

{% block title %}Account{% endblock %}

{% block content %}
<h1>Things were supposed to be here</h1>
<p><small>they appear to not be</small></p>

{% endblock %}

app/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="PokéPicker is a Pokémon team builder!">
    <meta name="author" content="Brendan Carlson">
    <title>{% block title %}{% endblock %} | PokéPicker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</head>

<body>
    <header class="header mb-5">
        <nav class="navbar navbar-expand-md bg-dark navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('main.home') }}">PokéPicker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                        {% if current_user.is_anonymous %}
                        <li class="nav-item">
                            <a class="nav-link {{ 'active' if title == 'Login' else ''}}"
                                href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {{ 'active' if title == 'Register' else ''}}"
                                href="{{ url_for('auth.register') }}">Register</a>
                        </li>
                        {% endif %}

                        {% if current_user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                {{ current_user.username }}
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{ url_for('user.profile') }}">Profile</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('user.account') }}">Account</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a></li>
                            </ul>
                        </li>
                        {% endif %}
                    </ul>

                    <form class="d-flex" role="search" action="{{ url_for('main.search') }}" method="POST">
                        <input class="form-control me-2" type="search" id="name" name="name"
                            placeholder="Search a pokémon" aria-label="Search">
                        <button class="btn btn-outline-warning" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <main class="main container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="flashes">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </main>
    <footer class="footer">{% block footer %}{% endblock %}</footer>
</body>

</html>

app/templates/components/card.html.j2
<div class="d-flex" style="justify-content: space-between; width: 80%; margin-inline: auto;">
    {% for poke in pokemon %}
    <div class="card" style="width: 18rem;">
        <img src="{{poke.sprite}}" class="card-img-top" alt="{{poke.name}}">
        <div class="card-body">
            <h5 class="card-title">{{poke.name.upper()}}</h5>
            <p class="card-text">{{poke.description}}</p>
            <div class="d-flex" style="justify-content: space-between;">
                <a href="#" class="btn btn-warning">PokéPick</a>
                <a href="{{ url_for(f'main.search/{poke.game_id}') }}" class="btn btn-info">More Info</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

app/templates/home.html.j2
{% extends 'base.html.j2' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if current_user.is_authenticated %}
<h1 style="font-size: 2rem; text-align: center; margin-block-end: 3rem;"> Welcome to PokéPicker! Start building your
    PokéDex by
    choosing your
    starter!</h1>
{% else %}
<h1 style="font-size: 2rem; text-align: center; margin-block-end: 3rem;"> Welcome to PokéPicker! Register your
    your account to start building your PokéDex!</h1>
{% endif %}
<div class="d-flex" style="justify-content: space-between; width: 80%; margin-inline: auto;">
    {% for poke in pokemon %}
    <div class="card" style="width: 18rem;">
        <img src="{{ poke.sprite }}" class="card-img-top" alt="{{ poke.name }}">
        <div class="card-body">
            <h5 class="card-title">{{poke.name.upper()}}</h5>
            <p class="card-text">{{poke.description}}</p>
            <div class="d-flex" style="justify-content: space-between;">
                <form action="{{ url_for('user.pick', id=poke.game_id) }}" method="POST">
                    <button type='submit' class="btn btn-warning">PokéPick</button>
                </form>
                <a href="{{ url_for('main.pokemon', game_id=poke.game_id) }}" class="btn btn-info">More Info</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/login.html.j2
{% extends 'base.html.j2' %}

{% block title %}Login{% endblock %}

{% block content %}

<section class="container">
    <form action="{{ url_for('auth.login') }}" method="POST">
        {# <input type="hidden" name="next" value="{{ 'next' if request.args.get() else '' }}"> #}

        <div class="mb-3">
            <label for="identifier" class="form-label">Email or Username</label>
            <input type="text/email" name="identifier" id="identifier" class="form-control">
        </div>

        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" name="password" id="password" class="form-control">
        </div>

        <div class="d-flex" style="justify-content: space-between;">
            <button type="submit" class="btn btn-warning">Sign In</button>
            <a class='btn btn-info' href="{{ url_for('auth.register') }}">New to PokéPicker? Register here!</a>
        </div>
    </form>
</section>

{% endblock %}

app/templates/profile.html.j2
{% extends 'base.html.j2' %}

{% block title %}{{user.username}}{% endblock %}

{% block content %}
<h1 style="text-align: center; font-size: 2rem; margin-block-end: 3rem;">{{user.username}}'s PokéDex</h1>
<div class="d-flex"
    style="flex-wrap: wrap; row-gap: 2rem; justify-content: space-between; width: 80%; margin-inline: auto;">
    {% for poke in pokemon %}
    <div class="card" style="width: 18rem;">
        <img src="{{ poke.sprite }}" class="card-img-top" alt="{{ poke.name }}">
        <div class="card-body">
            <h5 class="card-title">{{poke.name.upper()}}</h5>
            <p class="card-text">{{poke.description}}</p>
            <div class="d-flex" style="justify-content: space-between;">
                <form action="{{ url_for('user.pick', id=poke.game_id) }}" method="POST">
                    <button type='submit' class="btn btn-warning">PokéPick</button>
                </form>
                <a href="{{ url_for('main.pokemon', game_id=poke.game_id) }}" class="btn btn-info">More Info</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/register.html.j2
{% extends 'base.html.j2' %}

{% block title %}Register{% endblock %}

{% block content %}

<section class="container">
    <form action="{{ url_for('auth.register') }}" method="POST">
        {# <input type="hidden" name="next" value="{{ request.args.get('next', '') }}"> #}

        <div class="mb-3">
            <label for="firstName" class="form-label">First Name</label>
            <input type="text" name="firstName" id="firstName" class="form-control">
        </div>

        <div class="mb-3">
            <label for="lastName" class="form-label">Last Name</label>
            <input type="text" name="lastName" id="lastName" class="form-control">
        </div>

        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" name="username" id="username" class="form-control">
        </div>

        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" name="email" id="email" class="form-control">
        </div>

        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" name="password" id="password" class="form-control">
        </div>

        <div class="mb-3">
            <label for="confirmPassword" class="form-label">Confirm Password</label>
            <input type="password" name="confirmPassword" id="confirmPassword" class="form-control">
        </div>

        <button type="submit" class="btn btn-warning">Sign Up</button>
    </form>
</section>

{% endblock %}

app/templates/sign_in.html.j2
{% extends 'base.html.j2' %}

{% block content %}

<section class="container">
    <form action="{{ url_for('auth.sign_in') }}" method="POST">
        <input type="hidden" name="next" value="{{ request.args.get('next', '') }}">

        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" name="email" id="email" class="form-control">
        </div>

        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" name="password" id="password" class="form-control">
        </div>
        <button type="submit" class="btn btn-warning">Sign In</button>
    </form>
</section>

{% endblock %}

app/templates/sign_up.html.j2
{% extends 'base.html.j2' %}


{% block content %}

<section class="container">
    <form action="{{ url_for('auth.sign_up') }}" method="POST">
        <input type="hidden" name="next" value="{{ request.args.get('next', '') }}">

        <div class="mb-3">
            <label for="firstName" class="form-label">First Name</label>
            <input type="text" name="firstName" id="firstName" class="form-control">
        </div>

        <div class="mb-3">
            <label for="lastName" class="form-label">Last Name</label>
            <input type="text" name="lastName" id="lastName" class="form-control">
        </div>

        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" name="username" id="username" class="form-control">
        </div>

        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" name="email" id="email" class="form-control">
        </div>

        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" name="password" id="password" class="form-control">
        </div>

        <div class="mb-3">
            <label for="confirmPassword" class="form-label">Confirm Password</label>
            <input type="password" name="confirmPassword" id="confirmPassword" class="form-control">
        </div>

        <button type="submit" class="btn btn-warning">Sign Up</button>
    </form>
</section>

{% endblock %}

app/templates/single.html.j2
{% extends 'base.html.j2' %}

{% block title %}{{ pokemon.name.upper() }}{% endblock %}


{% block content %}
<div class="d-flex" style="justify-content: center; width: 80%; margin-inline: auto;">
    <div class="card" style="width: 18rem;">
        <img src="{{ pokemon.sprite }}" class="card-img-top" alt="{{ pokemon.name }}">
        <div class="card-body">
            <h5 class="card-title">{{ pokemon.name.upper() }}</h5>
            <p class="card-text">Types: {{ pokemon.types.title() }}</p>
            <p class="card-text">Abilities: {{ pokemon.abilities.title() }}</p>
            <p class="card-text">Height: {{ pokemon.height }}</p>
            <p class="card-text">Weight: {{ pokemon.weight }}</p>
            <p class="card-text">{{ pokemon.description }}</p>
            <form action="{{ url_for('user.pick', id=pokemon.game_id) }}" method="POST">
                <button type='submit' class="btn btn-warning">PokéPick</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}